import type { Metadata } from "next";
import { Roboto_Slab} from 'next/font/google';
import "./globals.css";

const robotoslab= Roboto_Slab({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
})






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${robotoslab}antialiased`}
      >
        {children}
     
      </body>
    </html>
  );
}
